- name: variables from PLAY level
  hosts: localhost
  vars_files:
  - variables.yaml
  vars:
    PERSON: "Siva from Play"
    WISHES: "Morning from PLAY"
  tasks:
  - name: check variables
    vars:
      PERSON: "Siva from tasks"
      WISHES: "Morning from tasks"
    ansible.builtin.debug:
      msg: "Hello {{PERSON}}, Good {{WISHES}}"