- name: variables from PLAY level
  hosts: localhost
  vars_files:
  - variables.yaml
  vars:
    PERSON: "Siva from Play"
    WISHES: "Morning from PLAY"
  tasks:
  - name: check variables
    vars:
      PERSON: "Siva from tasks"
      WISHES: "Morning from tasks"
    ansible.builtin.debug:
      msg: "Hello {{PERSON}}, Good {{WISHES}}"

      #1.CMD
      #2> tasks"
      #3 vars_files:
      #4.prompt
      #5..Play
      #6 invemntory
      