- name: condtions
  hosts: localhost
  tasks:
  - name: check roboshop users exits or not
    ansible.builtin.command: id roboshop
    register: user # user  is a variable name:
    ignore_errors: true


  - name: print variable value
    ansible.builtin.debug:
      msg: "user is {{user}}"

  - name: print exit status or return code
    ansible.builtin.debug:
      msg: "user is {{user.rc}}"

  - name: create user
    ansible.builtin.user:
      name: roboshop
    when: user.rc != 0 # condtion
