- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: install
    ansible.builtin.package:
      name: "{{item}}"
      state: present
     # msg: "{{item}}" # item is default value for loops
    loop:
    - git
    - nginx
    